<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
            http://maven.apache.org/POM/4.0.0
            https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.balance</groupId>
    <artifactId>balance-metalurgico</artifactId>
    <version>1.0.0</version>

    <name>Balance Metalúrgico</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>

        <javafx.version>21.0.2</javafx.version>
    </properties>

    <dependencies>

        <!-- Interfaz gráfica JavaFX -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
        </dependency>

    </dependencies>

    <build>

        <!-- El JAR generado tendrá este nombre -->
        <finalName>balance-metalurgico</finalName>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>

                <configuration>
                    <release>21</release>
                </configuration>
            </plugin>

            <!-- Ejecutar la aplicación JavaFX desde Maven -->
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>

                <configuration>
                    <mainClass>
                        com.balance.interfaz.Launcher
                    </mainClass>
                </configuration>
            </plugin>

            <!-- Clase principal del JAR -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.2</version>

                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>
                                com.balance.interfaz.Launcher
                            </mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

            <!-- Utilizado para copiar dependencias al empaquetar -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.8.1</version>
            </plugin>

        </plugins>
    </build>

</project>